export const potluckItems = [
  { id: "salad-green-1", label: "Grøn Salat", details: "Grøn salat (kål, bønner, salat, tomater etc.) til 4 personer" },
  { id: "salad-green-2", label: "Grøn Salat", details: "Grøn salat (kål, bønner, salat, tomater etc.) til 4 personer" },
  { id: "salad-green-3", label: "Grøn Salat", details: "Grøn salat (kål, bønner, salat, tomater etc.) til 4 personer" },
  { id: "salad-food-1", label: "Madsalat", details: "Madsalat (kartoffel, coucous, pasta etc.) til 4 personer" },
  { id: "salad-food-2", label: "Madsalat", details: "Madsalat (kartoffel, coucous, pasta etc.) til 4 personer" },
  { id: "salad-food-3", label: "Madsalat", details: "Madsalat (kartoffel, coucous, pasta etc.) til 4 personer" },
  { id: "sausage-1", label: "Pølser", details: "Pølser el. lign til 4 personer" },
  { id: "sausage-2", label: "Pølser", details: "Pølser el. lign til 4 personer" },
  { id: "sausage-3", label: "Pølser", details: "Pølser el. lign til 4 personer" },
  { id: "protein-1", label: "Kød/Protein", details: "Kød eller protein til 4 personer" },
  { id: "protein-2", label: "Kød/Protein", details: "Kød eller protein til 4 personer" },
  { id: "protein-3", label: "Kød/Protein", details: "Kød eller protein til 4 personer" },
  { id: "protein-4", label: "Kød/Protein", details: "Kød eller protein til 4 personer" },
  { id: "bread-1", label: "Brød", details: "Brød til 8 personer" },
  { id: "bread-2", label: "Brød", details: "Brød til 8 personer" },
  { id: "bread-3", label: "Brød", details: "Brød til 8 personer" }, 
  { id: "drinks-1", label: "Drinks", details: "Sodavand/limonade" },
  { id: "drinks-2", label: "Drinks", details: "Sodavand/limonade" },
  { id: "drinks-3", label: "Drinks", details: "Sodavand/limonade" },
  { id: "beer-1", label: "Øl", details: "Øl" },
  { id: "beer-2", label: "Øl", details: "Øl" },
  { id: "beer-3", label: "Øl", details: "Øl" },
  { id: "wine-1", label: "Vin", details: "Vin (Hvid)" },
  { id: "wine-2", label: "Vin", details: "Vin (Hvid)" },
  { id: "wine-3", label: "Vin", details: "Vin (Rød)" },
  { id: "wine-4", label: "Vin", details: "Vin (Rød)" },
];
